<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHic5cl4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHic5cl4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHic5cl4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHic5cl4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHic5cl4\appProdProjectContainer([
    'container.build_hash' => 'Hic5cl4',
    'container.build_id' => 'ac18bfe5',
    'container.build_time' => 1562084912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHic5cl4');
